// Training driver for the Cd/Cl surrogate model.
//
// Reads training_data.bin (generated by data_gen.py), trains a small MLP
// using MSE loss + AdamW, and saves weights to model.bin.
//
// Usage:
//   ./train [dataset/training_data.bin]

#include "tensor.hpp"
#include "autodiff.hpp"
#include "loss.hpp"
#include "optimizer.hpp"
#include "weights_io.hpp"
#include "layers/ad_linear.hpp"
#include "layers/ad_swiglu.hpp"
#include <algorithm>
#include <cassert>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <random>
#include <string>
#include <vector>

// ---------------------------------------------------------------------------
// Dataset loading
// ---------------------------------------------------------------------------

struct Sample {
    float wind_speed;
    float reynolds;
    float model_id;
    float cd;
    float cl;
};

struct Dataset {
    std::vector<Sample> samples;

    bool load(const std::string& path) {
        FILE* f = fopen(path.c_str(), "rb");
        if (!f) {
            fprintf(stderr, "Cannot open %s\n", path.c_str());
            return false;
        }

        uint32_t magic, version, num_records, num_features;
        if (fread(&magic, 4, 1, f) != 1 || magic != 0x4C415454) {
            fprintf(stderr, "Bad magic in %s\n", path.c_str());
            fclose(f);
            return false;
        }
        fread(&version, 4, 1, f);
        fread(&num_records, 4, 1, f);
        fread(&num_features, 4, 1, f);

        if (num_features != 5) {
            fprintf(stderr, "Expected 5 features per record, got %u\n",
                    num_features);
            fclose(f);
            return false;
        }

        samples.resize(num_records);
        for (uint32_t i = 0; i < num_records; ++i) {
            float rec[5];
            if (fread(rec, sizeof(float), 5, f) != 5) {
                fprintf(stderr, "Truncated file at record %u\n", i);
                fclose(f);
                return false;
            }
            samples[i] = {rec[0], rec[1], rec[2], rec[3], rec[4]};
        }

        fclose(f);
        return true;
    }
};

// ---------------------------------------------------------------------------
// Normalization: z-score per feature
// ---------------------------------------------------------------------------

struct Normalizer {
    float mean[3];
    float std_dev[3];

    void fit(const std::vector<Sample>& samples) {
        for (int j = 0; j < 3; ++j) {
            mean[j] = 0;
            std_dev[j] = 0;
        }
        int N = static_cast<int>(samples.size());
        for (auto& s : samples) {
            float feats[3] = {s.wind_speed, s.reynolds, s.model_id};
            for (int j = 0; j < 3; ++j)
                mean[j] += feats[j];
        }
        for (int j = 0; j < 3; ++j)
            mean[j] /= N;

        for (auto& s : samples) {
            float feats[3] = {s.wind_speed, s.reynolds, s.model_id};
            for (int j = 0; j < 3; ++j) {
                float d = feats[j] - mean[j];
                std_dev[j] += d * d;
            }
        }
        for (int j = 0; j < 3; ++j) {
            std_dev[j] = std::sqrt(std_dev[j] / N);
            if (std_dev[j] < 1e-8f) std_dev[j] = 1.0f;
        }
    }

    float normalize(float val, int feature) const {
        return (val - mean[feature]) / std_dev[feature];
    }
};

// ---------------------------------------------------------------------------
// Pack samples into [features x batch] tensors
// ---------------------------------------------------------------------------

static std::shared_ptr<ADTensor> pack_inputs(
    const std::vector<Sample>& samples,
    const std::vector<int>& indices,
    const Normalizer& norm) {
    int B = static_cast<int>(indices.size());
    Tensor t(3, B);
    for (int b = 0; b < B; ++b) {
        auto& s = samples[indices[b]];
        t(0, b) = norm.normalize(s.wind_speed, 0);
        t(1, b) = norm.normalize(s.reynolds, 1);
        t(2, b) = norm.normalize(s.model_id, 2);
    }
    return make_ad(t);
}

static std::shared_ptr<ADTensor> pack_targets(
    const std::vector<Sample>& samples,
    const std::vector<int>& indices) {
    int B = static_cast<int>(indices.size());
    Tensor t(2, B);
    for (int b = 0; b < B; ++b) {
        auto& s = samples[indices[b]];
        t(0, b) = s.cd;
        t(1, b) = s.cl;
    }
    return make_ad(t);
}

// ---------------------------------------------------------------------------
// Model: MLP with SwiGLU activations
//   Linear(3, 256) -> SwiGLU(256, 512)
//   -> Linear(256, 128) -> SwiGLU(128, 256)
//   -> Linear(128, 2)
// ---------------------------------------------------------------------------

struct SurrogateModel {
    ADLinear fc1{3, 256};
    ADSwiGLU act1{256, 512};
    ADLinear fc2{256, 128};
    ADSwiGLU act2{128, 256};
    ADLinear fc3{128, 2};

    std::shared_ptr<ADTensor> forward(const std::shared_ptr<ADTensor>& x) {
        auto h = act1.forward(fc1.forward(x));
        h = act2.forward(fc2.forward(h));
        return fc3.forward(h);
    }
};

// ---------------------------------------------------------------------------
// Evaluate on a set of indices, return mean L1 error for Cd and Cl
// ---------------------------------------------------------------------------

static void evaluate(SurrogateModel& model,
                     const std::vector<Sample>& samples,
                     const std::vector<int>& indices,
                     const Normalizer& norm,
                     float* cd_mae,
                     float* cl_mae) {
    auto x = pack_inputs(samples, indices, norm);
    auto pred = model.forward(x);

    int B = static_cast<int>(indices.size());
    float cd_err = 0, cl_err = 0;
    for (int b = 0; b < B; ++b) {
        cd_err += std::fabs(pred->val(0, b) - samples[indices[b]].cd);
        cl_err += std::fabs(pred->val(1, b) - samples[indices[b]].cl);
    }
    *cd_mae = cd_err / B;
    *cl_mae = cl_err / B;
}

// ---------------------------------------------------------------------------
// main
// ---------------------------------------------------------------------------

int main(int argc, char* argv[]) {
    std::string data_path = "dataset/training_data.bin";
    if (argc > 1) data_path = argv[1];

    printf("Loading dataset: %s\n", data_path.c_str());
    Dataset dataset;
    if (!dataset.load(data_path)) return 1;
    printf("Loaded %zu samples\n", dataset.samples.size());

    if (dataset.samples.size() < 10) {
        fprintf(stderr, "Need at least 10 samples to train\n");
        return 1;
    }

    // Shuffle and split 80/20
    std::vector<int> all_indices(dataset.samples.size());
    for (size_t i = 0; i < all_indices.size(); ++i)
        all_indices[i] = static_cast<int>(i);

    std::mt19937 rng(42);
    std::shuffle(all_indices.begin(), all_indices.end(), rng);

    int split = static_cast<int>(all_indices.size() * 0.8);
    std::vector<int> train_idx(all_indices.begin(),
                               all_indices.begin() + split);
    std::vector<int> val_idx(all_indices.begin() + split,
                             all_indices.end());

    printf("Train: %zu, Val: %zu\n", train_idx.size(), val_idx.size());

    // Fit normalizer on training set only
    Normalizer norm;
    {
        std::vector<Sample> train_samples;
        train_samples.reserve(train_idx.size());
        for (int i : train_idx)
            train_samples.push_back(dataset.samples[i]);
        norm.fit(train_samples);
    }
    printf("Normalizer: mean=[%.2f, %.1f, %.2f] std=[%.2f, %.1f, %.2f]\n",
           norm.mean[0], norm.mean[1], norm.mean[2],
           norm.std_dev[0], norm.std_dev[1], norm.std_dev[2]);

    // Build model
    SurrogateModel model;
    int num_params = 0;
    for (auto& p : get_parameters())
        num_params += p->val.numel();
    printf("Model parameters: %d\n", num_params);

    // Training config
    int epochs = 500;
    int batch_size = 64;
    float lr = 1e-3f;
    AdamW optimizer(lr, 0.9f, 0.999f, 1e-8f, 1e-4f, 1.0f);

    printf("\nTraining: %d epochs, batch=%d, lr=%.1e\n\n", epochs,
           batch_size, lr);

    float best_val_cd_mae = 1e9f;
    int patience = 0;
    int max_patience = 50;

    for (int epoch = 0; epoch < epochs; ++epoch) {
        // Shuffle training indices each epoch
        std::shuffle(train_idx.begin(), train_idx.end(), rng);

        float epoch_loss = 0;
        int num_batches = 0;

        for (int start = 0; start < static_cast<int>(train_idx.size());
             start += batch_size) {
            int end = std::min(start + batch_size,
                               static_cast<int>(train_idx.size()));
            std::vector<int> batch_idx(train_idx.begin() + start,
                                       train_idx.begin() + end);

            optimizer.zero_grad();

            auto x = pack_inputs(dataset.samples, batch_idx, norm);
            auto y = pack_targets(dataset.samples, batch_idx);
            auto pred = model.forward(x);
            auto loss = mse_loss(pred, y);

            loss->backward();
            optimizer.step();

            epoch_loss += loss->val.data[0];
            num_batches++;

            if (std::isnan(loss->val.data[0]) || std::isinf(loss->val.data[0])) {
                fprintf(stderr, "NaN/Inf loss at epoch %d, aborting\n", epoch);
                return 1;
            }
        }

        epoch_loss /= num_batches;

        // Validate every 10 epochs
        if (epoch % 10 == 0 || epoch == epochs - 1) {
            float cd_mae, cl_mae;
            evaluate(model, dataset.samples, val_idx, norm,
                     &cd_mae, &cl_mae);

            printf("epoch %3d  loss=%.6f  val_cd_mae=%.4f  "
                   "val_cl_mae=%.4f",
                   epoch, epoch_loss, cd_mae, cl_mae);

            if (cd_mae < best_val_cd_mae) {
                best_val_cd_mae = cd_mae;
                patience = 0;
                save_weights("model.bin");
                printf("  *saved*");
            } else {
                patience += 10;
            }
            printf("\n");

            if (patience >= max_patience) {
                printf("Early stopping at epoch %d\n", epoch);
                break;
            }
        }
    }

    // Reload best weights and print final metrics
    load_weights("model.bin");

    float cd_mae, cl_mae;
    evaluate(model, dataset.samples, val_idx, norm, &cd_mae, &cl_mae);
    printf("\nFinal validation: Cd MAE=%.4f, Cl MAE=%.4f\n",
           cd_mae, cl_mae);

    // Also print some example predictions
    printf("\nSample predictions (val set):\n");
    printf("  %-8s %-8s %-6s | %-8s %-8s | %-8s %-8s\n",
           "wind", "Re", "model", "true_Cd", "true_Cl",
           "pred_Cd", "pred_Cl");
    printf("  %-8s %-8s %-6s | %-8s %-8s | %-8s %-8s\n",
           "------", "------", "----", "------", "------",
           "------", "------");

    int show = std::min(10, static_cast<int>(val_idx.size()));
    auto x_show = pack_inputs(dataset.samples, val_idx, norm);
    auto pred_show = model.forward(x_show);
    for (int i = 0; i < show; ++i) {
        auto& s = dataset.samples[val_idx[i]];
        printf("  %-8.2f %-8.0f %-6.0f | %-8.3f %-8.3f | %-8.3f %-8.3f\n",
               s.wind_speed, s.reynolds, s.model_id,
               s.cd, s.cl,
               pred_show->val(0, i), pred_show->val(1, i));
    }

    // Save normalizer alongside weights so inference can use it
    {
        FILE* f = fopen("model_norm.bin", "wb");
        if (f) {
            fwrite(norm.mean, sizeof(float), 3, f);
            fwrite(norm.std_dev, sizeof(float), 3, f);
            fclose(f);
            printf("\nNormalizer saved to model_norm.bin\n");
        }
    }

    printf("Weights saved to model.bin\n");
    return 0;
}
