"""
Shape optimization data generation pipeline.

Generates FFD-deformed meshes, submits them to the Modal render endpoint
as custom OBJ models, collects Cd/Cl results, and saves the dataset as
binary (.sobin) and CSV.

Usage:
    python gen_shapes.py --config shapeopt_config.yaml --endpoint https://...
    python gen_shapes.py --config shapeopt_config.yaml --endpoint https://... --resume
    python gen_shapes.py --status
    python gen_shapes.py --export-only
"""

import argparse
import base64
import csv
import hashlib
import io
import json
import struct
import sys
import time
from pathlib import Path

import numpy as np
import requests
import yaml

from ffd import FFDLattice, load_obj, save_obj, compute_bbox

# Paths

PROJECT_ROOT = Path(__file__).resolve().parents[2]
SHAPEOPT_DIR = Path(__file__).resolve().parent
DATASET_DIR = SHAPEOPT_DIR / "dataset"
MANIFEST_FILE = DATASET_DIR / "manifest.csv"
RESULTS_FILE = DATASET_DIR / "results.csv"
SOBIN_FILE = DATASET_DIR / "shapeopt_data.sobin"
STATS_FILE = DATASET_DIR / "stats.json"

MODEL_OBJ_PATHS = {
    "ahmed25": PROJECT_ROOT / "simulation" / "assets" / "3d-files" / "ahmed_25deg_m.obj",
    "ahmed35": PROJECT_ROOT / "simulation" / "assets" / "3d-files" / "ahmed_35deg_m.obj",
    "car": PROJECT_ROOT / "simulation" / "assets" / "3d-files" / "car-model.obj",
}

SOBIN_MAGIC = 0x534F5054
SOBIN_VERSION = 1


# Config

def load_config(config_path: str) -> dict:
    with open(config_path) as f:
        return yaml.safe_load(f)


# OBJ encoding

def obj_to_base64(vertices: np.ndarray, faces: np.ndarray) -> str:
    """Encode a mesh as a base64 OBJ string for the Modal endpoint."""
    buf = io.StringIO()
    buf.write("# Generated by ml/shapeopt/gen_shapes.py\n")
    for v in vertices:
        buf.write(f"v {v[0]:.8f} {v[1]:.8f} {v[2]:.8f}\n")
    for face in faces:
        buf.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")
    return base64.b64encode(buf.getvalue().encode("utf-8")).decode("ascii")


# Modal submission with async polling

def submit_job(endpoint: str, payload: dict, timeout: int = 30) -> str | None:
    """POST to the render endpoint. Returns a job_id on success, None on error."""
    try:
        resp = requests.post(endpoint, json=payload, timeout=timeout)
        resp.raise_for_status()
        data = resp.json()
        if data.get("status") == "accepted":
            return data["job_id"]
        # Some endpoints return the result directly (synchronous mode)
        if data.get("status") == "complete":
            return data
        print(f"  Unexpected response: {data}", file=sys.stderr)
        return None
    except Exception as e:
        print(f"  Submit failed: {e}", file=sys.stderr)
        return None


def poll_job(endpoint: str, job_id: str, poll_interval: float = 5.0,
             timeout: float = 1800.0) -> dict | None:
    """
    Poll the job_status endpoint until the job finishes or times out.

    The status endpoint is derived from the render endpoint by replacing
    the trailing path component. For example:
        render:  https://x.modal.run/render_endpoint
        status:  https://x.modal.run/job_status?job_id=...
    """
    # Build the status URL from the render endpoint
    base = endpoint.rsplit("/", 1)[0]
    status_url = f"{base}/job_status"

    t0 = time.monotonic()
    while time.monotonic() - t0 < timeout:
        try:
            resp = requests.get(
                status_url, params={"job_id": job_id}, timeout=30
            )
            resp.raise_for_status()
            data = resp.json()

            status = data.get("status")
            if status == "complete":
                return data
            if status == "error":
                return data
            # Still rendering, keep waiting
        except requests.RequestException as e:
            print(f"  Poll error (will retry): {e}", file=sys.stderr)

        time.sleep(poll_interval)

    return {"status": "error", "error": f"Timed out after {timeout}s"}


def run_simulation(endpoint: str, payload: dict) -> dict:
    """Submit a job and poll for results. Returns the result dict."""
    result = submit_job(endpoint, payload)

    # submit_job returned a full result dict (synchronous endpoint)
    if isinstance(result, dict):
        return result

    if result is None:
        return {"status": "error", "error": "Failed to submit job"}

    job_id = result
    poll_result = poll_job(endpoint, job_id)
    if poll_result is None:
        return {"status": "error", "error": "Polling returned None"}
    return poll_result


# Sample tracking

def sample_id(model: str, idx: int) -> str:
    key = f"shapeopt_{model}_{idx}"
    return hashlib.md5(key.encode()).hexdigest()[:12]


def load_completed_samples() -> set[str]:
    if not MANIFEST_FILE.exists():
        return set()
    completed = set()
    with open(MANIFEST_FILE) as f:
        reader = csv.DictReader(f)
        for row in reader:
            if row.get("status") == "complete":
                completed.add(row["sample_id"])
    return completed


def save_manifest_row(sid: str, model: str, idx: int, status: str,
                      cd: float | None, cl: float | None,
                      error: str | None = None):
    DATASET_DIR.mkdir(parents=True, exist_ok=True)
    write_header = not MANIFEST_FILE.exists()
    with open(MANIFEST_FILE, "a", newline="") as f:
        writer = csv.writer(f)
        if write_header:
            writer.writerow([
                "sample_id", "model", "sample_idx", "status",
                "cd_value", "cl_value", "error",
            ])
        writer.writerow([
            sid, model, idx, status,
            f"{cd:.6f}" if cd is not None else "",
            f"{cl:.6f}" if cl is not None else "",
            error or "",
        ])


def save_results_row(sid: str, model: str, idx: int,
                     displacements: np.ndarray, cd: float, cl: float):
    DATASET_DIR.mkdir(parents=True, exist_ok=True)
    write_header = not RESULTS_FILE.exists()
    with open(RESULTS_FILE, "a", newline="") as f:
        writer = csv.writer(f)
        if write_header:
            writer.writerow([
                "sample_id", "model", "sample_idx",
                "cd_value", "cl_value", "displacements",
            ])
        writer.writerow([
            sid, model, idx,
            f"{cd:.6f}", f"{cl:.6f}",
            json.dumps(displacements.tolist()),
        ])


# Binary export (.sobin)

def export_sobin(results_file: Path, output_file: Path):
    """
    Convert CSV results to .sobin binary format.

    Header (20 bytes):
        uint32 magic = 0x534F5054
        uint32 version = 1
        uint32 num_samples
        uint32 num_ffd_params
        uint32 num_outputs = 2

    Per sample:
        float32[num_ffd_params] ffd_displacements
        float32[2] [cd, cl]
    """
    if not results_file.exists():
        print("No results file found, skipping binary export.")
        return 0

    records = []
    with open(results_file) as f:
        reader = csv.DictReader(f)
        for row in reader:
            if not row["cd_value"] or not row["cl_value"]:
                continue
            disps = np.array(json.loads(row["displacements"]), dtype=np.float32)
            cd = float(row["cd_value"])
            cl = float(row["cl_value"])
            records.append((disps, cd, cl))

    if not records:
        print("No valid records found.")
        return 0

    num_ffd_params = len(records[0][0])
    # Verify all records have the same parameter count
    for i, (d, _, _) in enumerate(records):
        if len(d) != num_ffd_params:
            print(
                f"WARNING: Sample {i} has {len(d)} params, expected {num_ffd_params}. Skipping.",
                file=sys.stderr,
            )
            continue

    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, "wb") as f:
        f.write(struct.pack("<I", SOBIN_MAGIC))
        f.write(struct.pack("<I", SOBIN_VERSION))
        f.write(struct.pack("<I", len(records)))
        f.write(struct.pack("<I", num_ffd_params))
        f.write(struct.pack("<I", 2))  # num_outputs (cd, cl)

        for disps, cd, cl in records:
            f.write(disps.astype(np.float32).tobytes())
            f.write(struct.pack("<ff", cd, cl))

    size_kb = output_file.stat().st_size / 1024
    print(f"Exported {len(records)} samples to {output_file} ({size_kb:.1f} KB)")
    print(f"  FFD params per sample: {num_ffd_params}")
    return len(records)


# Main pipeline

def run_sweep(config_path: str, endpoint: str, resume: bool = False):
    config = load_config(config_path)

    base_models = config["base_models"]
    n_control = tuple(config["ffd_grid"])
    num_samples = config["num_samples"]
    max_fraction = config["displacement_range"]
    symmetric = config.get("enforce_symmetry", True)
    wind_speed = config["wind_speed"]
    reynolds = config["reynolds"]
    duration = config["duration"]
    collision_mode = config.get("collision_mode", 2)
    retry_limit = config.get("retry_limit", 3)

    completed = load_completed_samples() if resume else set()

    for model in base_models:
        obj_path = MODEL_OBJ_PATHS.get(model)
        if obj_path is None or not obj_path.exists():
            print(f"ERROR: OBJ not found for model '{model}' at {obj_path}", file=sys.stderr)
            continue

        print(f"\n{'='*60}")
        print(f"Model: {model}")
        print(f"OBJ: {obj_path}")
        print(f"{'='*60}")

        vertices, faces = load_obj(str(obj_path))
        bbox_min, bbox_max = compute_bbox(vertices)
        lattice = FFDLattice(bbox_min, bbox_max, n_control=n_control)

        num_params = lattice.get_num_params()
        print(f"  Vertices: {len(vertices)}")
        print(f"  FFD grid: {n_control}, total params: {num_params}")
        print(f"  Samples to generate: {num_samples + 1} (baseline + {num_samples} deformed)")

        # Generate LHS samples
        print(f"  Generating {num_samples} LHS samples...")
        lhs_samples = lattice.sample_random(
            num_samples, max_fraction=max_fraction, symmetric=symmetric
        )

        # Prepend the baseline (zero displacements) as sample 0
        baseline = np.zeros((1, num_params), dtype=np.float64)
        all_samples = np.vstack([baseline, lhs_samples])

        success = 0
        failed = 0

        for idx in range(len(all_samples)):
            sid = sample_id(model, idx)

            if sid in completed:
                success += 1
                continue

            displacements = all_samples[idx]
            tag = "baseline" if idx == 0 else f"sample {idx}/{num_samples}"

            # Deform the mesh
            deformed = lattice.deform(vertices, displacements)

            # Encode as base64 OBJ
            obj_b64 = obj_to_base64(deformed, faces)

            payload = {
                "job_id": f"shapeopt_{model}_{idx}",
                "wind_speed": wind_speed,
                "reynolds": reynolds,
                "duration": duration,
                "collision_mode": collision_mode,
                "model": "custom",
                "obj_data": obj_b64,
                "viz_mode": 1,
            }

            # Submit with retries
            result = None
            for attempt in range(retry_limit):
                result = run_simulation(endpoint, payload)
                if result.get("status") == "complete":
                    break
                if attempt < retry_limit - 1:
                    print(f"    Retry {attempt + 1} for {tag}...")
                    time.sleep(2.0)

            cd = result.get("cd_value") if result else None
            cl = result.get("cl_value") if result else None
            status = result.get("status", "error") if result else "error"
            error = result.get("error") if result else "submit failed"

            if status == "complete" and cd is not None:
                save_manifest_row(sid, model, idx, "complete", cd, cl)
                save_results_row(sid, model, idx, displacements.astype(np.float32), cd, cl)
                success += 1
                print(
                    f"  [{success + failed}/{len(all_samples)}] {tag} "
                    f"-> Cd={cd:.4f}, Cl={cl:.4f}"
                )
            else:
                save_manifest_row(sid, model, idx, "error", None, None, error=str(error))
                failed += 1
                print(
                    f"  [{success + failed}/{len(all_samples)}] {tag} "
                    f"-> FAILED: {error}"
                )

        print(f"\n  {model}: {success} complete, {failed} failed")

    # Export binary
    n_exported = export_sobin(RESULTS_FILE, SOBIN_FILE)
    if n_exported:
        compute_stats()


def compute_stats():
    """Generate summary statistics."""
    if not MANIFEST_FILE.exists():
        return

    stats = {"total": 0, "complete": 0, "failed": 0, "by_model": {}}
    with open(MANIFEST_FILE) as f:
        reader = csv.DictReader(f)
        for row in reader:
            stats["total"] += 1
            if row["status"] == "complete":
                stats["complete"] += 1
            else:
                stats["failed"] += 1

            model = row["model"]
            if model not in stats["by_model"]:
                stats["by_model"][model] = {"count": 0, "cd_values": []}
            stats["by_model"][model]["count"] += 1
            if row["cd_value"]:
                stats["by_model"][model]["cd_values"].append(float(row["cd_value"]))

    for model_stats in stats["by_model"].values():
        cd_vals = model_stats.pop("cd_values")
        if cd_vals:
            model_stats["cd_mean"] = sum(cd_vals) / len(cd_vals)
            model_stats["cd_min"] = min(cd_vals)
            model_stats["cd_max"] = max(cd_vals)
            mean = model_stats["cd_mean"]
            model_stats["cd_std"] = (
                sum((x - mean) ** 2 for x in cd_vals) / len(cd_vals)
            ) ** 0.5

    DATASET_DIR.mkdir(parents=True, exist_ok=True)
    with open(STATS_FILE, "w") as f:
        json.dump(stats, f, indent=2)

    print(f"\nStats: {stats['complete']} complete, {stats['failed']} failed")
    for model, ms in stats["by_model"].items():
        if "cd_mean" in ms:
            print(f"  {model}: {ms['count']} samples, Cd mean={ms['cd_mean']:.4f} std={ms['cd_std']:.4f}")

    return stats


def show_status():
    stats = compute_stats()
    if not stats:
        print("No data generated yet.")
        return

    print(f"Total samples: {stats['total']}")
    print(f"  Complete: {stats['complete']}")
    print(f"  Failed: {stats['failed']}")
    for model, ms in stats["by_model"].items():
        print(f"  {model}: {ms['count']} samples", end="")
        if "cd_mean" in ms:
            print(f", Cd mean={ms['cd_mean']:.4f} std={ms['cd_std']:.4f}")
        else:
            print()

    if SOBIN_FILE.exists():
        size_kb = SOBIN_FILE.stat().st_size / 1024
        print(f"\n  Binary: {SOBIN_FILE} ({size_kb:.1f} KB)")


# CLI

def main():
    parser = argparse.ArgumentParser(
        description="Generate FFD shape optimization training data"
    )
    parser.add_argument(
        "--config",
        default="shapeopt_config.yaml",
        help="Config YAML file (default: shapeopt_config.yaml)",
    )
    parser.add_argument(
        "--endpoint", default=None,
        help="Modal render endpoint URL",
    )
    parser.add_argument(
        "--resume", action="store_true",
        help="Skip already-completed samples",
    )
    parser.add_argument(
        "--status", action="store_true",
        help="Show data generation progress",
    )
    parser.add_argument(
        "--export-only", action="store_true",
        help="Re-export .sobin from existing CSV results",
    )
    args = parser.parse_args()

    if args.status:
        show_status()
        return

    if args.export_only:
        export_sobin(RESULTS_FILE, SOBIN_FILE)
        compute_stats()
        return

    endpoint = args.endpoint
    if not endpoint:
        import os
        endpoint = os.environ.get("MODAL_RENDER_ENDPOINT")
    if not endpoint:
        print(
            "Error: provide --endpoint or set MODAL_RENDER_ENDPOINT",
            file=sys.stderr,
        )
        sys.exit(1)

    config_path = SHAPEOPT_DIR / args.config
    if not config_path.exists():
        print(f"Error: config not found at {config_path}", file=sys.stderr)
        sys.exit(1)

    run_sweep(str(config_path), endpoint, resume=args.resume)


if __name__ == "__main__":
    main()
