"""
FFD shape optimization via gradient descent through the trained surrogate.

Loads a trained ShapeOptSurrogate checkpoint, runs Adam on the FFD
displacement parameters to minimize predicted Cd, then exports the
optimized mesh as OBJ. Optionally validates the result against an
actual LBM simulation on Modal.

Usage:
    python optimize.py --weights dataset/shapeopt_model_best.pt --base-model ahmed25 --output optimized.obj
    python optimize.py --weights dataset/shapeopt_model_best.pt --base-model ahmed25 --validate --endpoint https://...
"""

import argparse
import base64
import io
import sys
import time
from pathlib import Path

import numpy as np
import requests
import torch
import torch.nn.functional as F

from ffd import FFDLattice, load_obj, save_obj, compute_bbox

PROJECT_ROOT = Path(__file__).resolve().parents[2]

MODEL_OBJ_PATHS = {
    "ahmed25": PROJECT_ROOT / "simulation" / "assets" / "3d-files" / "ahmed_25deg_m.obj",
    "ahmed35": PROJECT_ROOT / "simulation" / "assets" / "3d-files" / "ahmed_35deg_m.obj",
    "car": PROJECT_ROOT / "simulation" / "assets" / "3d-files" / "car-model.obj",
}


# ---------------------------------------------------------------------------
# Model definition (must match train_shapeopt.py)
# ---------------------------------------------------------------------------

class SwiGLU(torch.nn.Module):
    def __init__(self, in_dim: int, hidden_dim: int):
        super().__init__()
        self.w_gate = torch.nn.Linear(in_dim, hidden_dim, bias=False)
        self.w_up = torch.nn.Linear(in_dim, hidden_dim, bias=False)
        self.w_down = torch.nn.Linear(hidden_dim, in_dim, bias=False)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.w_down(F.silu(self.w_gate(x)) * self.w_up(x))


class ShapeOptSurrogate(torch.nn.Module):
    def __init__(self, input_dim: int):
        super().__init__()
        self.fc1 = torch.nn.Linear(input_dim, 256)
        self.swiglu1 = SwiGLU(256, 512)
        self.fc2 = torch.nn.Linear(256, 128)
        self.swiglu2 = SwiGLU(128, 256)
        self.fc3 = torch.nn.Linear(128, 2)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        h = self.fc1(x)
        h = self.swiglu1(h)
        h = self.fc2(h)
        h = self.swiglu2(h)
        return self.fc3(h)


# ---------------------------------------------------------------------------
# Modal submission helpers (same pattern as gen_shapes.py)
# ---------------------------------------------------------------------------

def obj_to_base64(vertices: np.ndarray, faces: np.ndarray) -> str:
    buf = io.StringIO()
    buf.write("# Generated by ml/shapeopt/optimize.py\n")
    for v in vertices:
        buf.write(f"v {v[0]:.8f} {v[1]:.8f} {v[2]:.8f}\n")
    for face in faces:
        buf.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")
    return base64.b64encode(buf.getvalue().encode("utf-8")).decode("ascii")


def submit_and_poll(endpoint: str, payload: dict,
                    poll_interval: float = 5.0, timeout: float = 1800.0) -> dict:
    """Submit a render job and poll until completion."""
    try:
        resp = requests.post(endpoint, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
    except Exception as e:
        return {"status": "error", "error": f"Submit failed: {e}"}

    if data.get("status") == "complete":
        return data

    if data.get("status") != "accepted":
        return {"status": "error", "error": f"Unexpected response: {data}"}

    job_id = data["job_id"]
    base = endpoint.rsplit("/", 1)[0]
    status_url = f"{base}/job_status"

    t0 = time.monotonic()
    while time.monotonic() - t0 < timeout:
        try:
            resp = requests.get(status_url, params={"job_id": job_id}, timeout=30)
            resp.raise_for_status()
            result = resp.json()
            if result.get("status") in ("complete", "error"):
                return result
        except requests.RequestException as e:
            print(f"  Poll error (will retry): {e}", file=sys.stderr)
        time.sleep(poll_interval)

    return {"status": "error", "error": f"Timed out after {timeout}s"}


# ---------------------------------------------------------------------------
# Optimization
# ---------------------------------------------------------------------------

def optimize(args):
    # Load base mesh
    obj_path = MODEL_OBJ_PATHS.get(args.base_model)
    if obj_path is None or not obj_path.exists():
        print(f"Error: OBJ not found for model '{args.base_model}' at {obj_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Base model: {args.base_model}")
    print(f"OBJ: {obj_path}")

    vertices, faces = load_obj(str(obj_path))
    print(f"  Vertices: {len(vertices)}, Faces: {len(faces)}")

    # Load checkpoint
    print(f"Loading weights: {args.weights}")
    ckpt = torch.load(args.weights, map_location="cpu", weights_only=False)

    input_dim = ckpt["input_dim"]
    num_ffd_params = ckpt["num_ffd_params"]
    feat_mean = torch.from_numpy(ckpt["feat_mean"]).float()
    feat_std = torch.from_numpy(ckpt["feat_std"]).float()

    print(f"  Input dim: {input_dim}")
    print(f"  FFD params: {num_ffd_params}")
    print(f"  Best val Cd MAE: {ckpt.get('best_val_cd_mae', 'N/A')}")

    model = ShapeOptSurrogate(input_dim)
    model.load_state_dict(ckpt["model_state_dict"])
    model.eval()

    # Set up FFD lattice
    # Infer grid shape from num_ffd_params. The config uses ffd_grid [4,3,3],
    # so num_params = 4*3*3*3 = 108. We try to recover it, but fall back
    # to the default if the numbers don't match.
    ffd_grid = args.ffd_grid
    expected_params = ffd_grid[0] * ffd_grid[1] * ffd_grid[2] * 3
    if expected_params != num_ffd_params:
        print(
            f"Error: FFD grid {ffd_grid} gives {expected_params} params "
            f"but checkpoint expects {num_ffd_params}",
            file=sys.stderr,
        )
        sys.exit(1)

    bbox_min, bbox_max = compute_bbox(vertices)
    lattice = FFDLattice(bbox_min, bbox_max, n_control=ffd_grid)
    max_fraction = args.max_displacement

    print(f"  FFD grid: {ffd_grid}")
    print(f"  Max displacement: {max_fraction} * bbox extent")

    # Optimization variables
    displacements = torch.zeros(num_ffd_params, requires_grad=True)
    optimizer = torch.optim.Adam([displacements], lr=args.lr)

    wind_speed_val = args.wind_speed
    reynolds_val = args.reynolds
    extra = torch.tensor([wind_speed_val, reynolds_val], dtype=torch.float32)

    # Numpy lattice for clamping and symmetry enforcement
    extent_torch = torch.from_numpy(lattice.extent).float()
    limits = max_fraction * extent_torch

    print(f"\nOptimizing: {args.steps} steps, lr={args.lr}")
    print(f"  Wind speed: {wind_speed_val}, Reynolds: {reynolds_val}")
    print(f"{'Step':>6s}  {'Cd':>10s}  {'Cl':>10s}  {'|disp|_max':>12s}")
    print("-" * 44)

    trajectory = []

    for step in range(args.steps):
        optimizer.zero_grad()

        # Clamp displacements to physical limits
        with torch.no_grad():
            d_4d = displacements.view(
                lattice.nx, lattice.ny, lattice.nz, 3
            )
            for comp in range(3):
                d_4d[..., comp].clamp_(-limits[comp].item(), limits[comp].item())

            # Enforce bilateral symmetry
            d_np = displacements.detach().numpy().copy()
            d_sym = lattice.enforce_symmetry(d_np, axis=1)
            displacements.data.copy_(torch.from_numpy(d_sym).float())

        # Build input: normalize (displacements + extra features)
        inp = torch.cat([displacements, extra])
        inp_norm = (inp - feat_mean) / feat_std
        inp_norm = inp_norm.unsqueeze(0)  # batch dim

        pred = model(inp_norm)
        cd_pred = pred[0, 0]
        cl_pred = pred[0, 1]

        # Minimize Cd
        loss = cd_pred
        loss.backward()
        optimizer.step()

        cd_val = cd_pred.item()
        cl_val = cl_pred.item()
        max_disp = displacements.abs().max().item()
        trajectory.append((step, cd_val, cl_val, max_disp))

        if step % 20 == 0 or step == args.steps - 1:
            print(f"{step:6d}  {cd_val:10.6f}  {cl_val:10.6f}  {max_disp:12.6f}")

    # Final clamp and symmetry
    with torch.no_grad():
        d_np = displacements.detach().numpy().copy()
        d_np = lattice.clamp_displacements(d_np, max_fraction=max_fraction)
        d_np = lattice.enforce_symmetry(d_np, axis=1)

    # Report optimization trajectory
    cd_start = trajectory[0][1]
    cd_end = trajectory[-1][1]
    print(f"\nOptimization complete.")
    print(f"  Cd: {cd_start:.6f} -> {cd_end:.6f} (delta = {cd_end - cd_start:+.6f})")
    if cd_start > 1e-9:
        print(f"  Relative Cd reduction: {(cd_end - cd_start) / cd_start * 100:+.2f}%")

    # Deform and export mesh
    deformed = lattice.deform(vertices, d_np)
    output_path = args.output
    save_obj(output_path, deformed, faces)
    print(f"  Optimized mesh: {output_path}")

    # Validation against actual LBM
    if args.validate:
        if not args.endpoint:
            print("Error: --validate requires --endpoint", file=sys.stderr)
            sys.exit(1)

        print(f"\nValidating against LBM simulation...")
        print(f"  Endpoint: {args.endpoint}")

        obj_b64 = obj_to_base64(deformed, faces)
        payload = {
            "job_id": "shapeopt_validate",
            "wind_speed": wind_speed_val,
            "reynolds": reynolds_val,
            "duration": 15,
            "collision_mode": 2,
            "model": "custom",
            "obj_data": obj_b64,
            "viz_mode": 1,
        }

        result = submit_and_poll(args.endpoint, payload)

        if result.get("status") == "complete":
            lbm_cd = result.get("cd_value")
            lbm_cl = result.get("cl_value")
            print(f"  LBM Cd: {lbm_cd:.6f}")
            print(f"  LBM Cl: {lbm_cl:.6f}")
            print(f"  Surrogate Cd: {cd_end:.6f}")
            if lbm_cd is not None:
                print(f"  Cd error (surrogate - LBM): {cd_end - lbm_cd:+.6f}")
                if abs(lbm_cd) > 1e-9:
                    print(f"  Cd relative error: {(cd_end - lbm_cd) / lbm_cd * 100:+.2f}%")
        else:
            print(f"  Validation failed: {result.get('error', 'unknown')}", file=sys.stderr)

    # Print full trajectory if requested
    if args.verbose:
        print(f"\nFull trajectory:")
        print(f"{'Step':>6s}  {'Cd':>10s}  {'Cl':>10s}  {'|disp|_max':>12s}")
        print("-" * 44)
        for step, cd, cl, md in trajectory:
            print(f"{step:6d}  {cd:10.6f}  {cl:10.6f}  {md:12.6f}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Optimize shape via gradient descent through the surrogate"
    )
    parser.add_argument(
        "--weights", required=True,
        help="Path to trained PyTorch checkpoint (.pt)",
    )
    parser.add_argument(
        "--base-model", required=True, choices=["ahmed25", "ahmed35", "car"],
        help="Base model to deform",
    )
    parser.add_argument(
        "--output", default="optimized.obj",
        help="Output OBJ path (default: optimized.obj)",
    )
    parser.add_argument(
        "--wind-speed", type=float, default=1.0,
        help="Wind speed for optimization (default: 1.0)",
    )
    parser.add_argument(
        "--reynolds", type=float, default=10000,
        help="Reynolds number for optimization (default: 10000)",
    )
    parser.add_argument(
        "--steps", type=int, default=200,
        help="Number of optimization steps (default: 200)",
    )
    parser.add_argument(
        "--lr", type=float, default=0.01,
        help="Adam learning rate (default: 0.01)",
    )
    parser.add_argument(
        "--ffd-grid", type=int, nargs=3, default=[4, 3, 3],
        help="FFD control point grid (default: 4 3 3)",
        metavar=("NX", "NY", "NZ"),
    )
    parser.add_argument(
        "--max-displacement", type=float, default=0.15,
        help="Max displacement as fraction of bbox extent (default: 0.15)",
    )
    parser.add_argument(
        "--validate", action="store_true",
        help="Submit optimized mesh to Modal for LBM validation",
    )
    parser.add_argument(
        "--endpoint", default=None,
        help="Modal render endpoint URL (required for --validate)",
    )
    parser.add_argument(
        "--verbose", action="store_true",
        help="Print full optimization trajectory",
    )
    args = parser.parse_args()

    if not Path(args.weights).exists():
        print(f"Error: weights not found at {args.weights}", file=sys.stderr)
        sys.exit(1)

    optimize(args)


if __name__ == "__main__":
    main()
